import os

clear = lambda: os.system("cls")
clear()
os.system("python -m pip install --upgrade pip")
clear()
os.system("pip install tkinter")
clear()
os.system("pip install colorama")
clear()

import time
from subprocess import call

os.system("pip install discord")
clear()
os.system("pip install arg")
clear()
os.system("pip install requests")
clear()
os.system("pip install pystyle")
clear()
os.system("pip install tqdm")
clear()
os.system("pip install selenium")
clear()
os.system("pip install aiohttp")
clear()
os.system("pip install asyncio")
clear()
os.system("pip install tasksio")
clear()
os.system("pip install ab5")
clear()
os.system("pip install tls_client")
clear()
os.system("pip install keyboard")
clear()
os.system("pip install phonenumbers")
clear()
os.system("pip install folium")
clear()
os.system("pip install discum")
clear()
os.system("pip install secrets")
clear()
os.system("pip install email")
clear()
os.system("pip install datetime")
clear()
os.system("pip install websocket")
clear()
os.system("pip install pytube")
clear()
os.system("pip install pynput")
clear()
os.system("pip install playsound")
clear()
os.system("pip install pycryptodome")
clear()
os.system("pip install pypiwin32")
clear()
os.system("pip install psutil")
clear()
os.system("pip install pyotp")
clear()
os.system("pip install dhooks")
clear()
os.system("pip install tkinter")
clear()
os.system("pip install auto_py_to_exe")
clear()
os.system("pip install fade")
clear()
os.system("pip install functools")
clear()
os.system("pip install hashlib")
clear()
os.system("pip install pwinput")
clear()
os.system("pip install opencage")
clear()
os.system("pip install bs4")
clear()
os.system("pip install youtube_dl")
clear()
os.system("pip install nextcord")
clear()
os.system("pip install websockets")
clear()
os.system("pip install rsa")
clear()
os.system("pip install padding")
clear()
os.system("pip install urlopen")
clear()
os.system("pip install origin")
clear()
os.system("pip install hashes")
clear()
os.system("pip install httpx")
clear()
os.system("pip install fade")
clear()
os.system("pip install capmonster_python")
clear()
os.system("pip install tls_client")
clear()
print("SUCCESSFULLY DOWNLOADED ALL USEFULL IMPORTS!")
time.sleep(3)
exit

